### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Matt561/zsh-nhl-schedule#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Matt561** [comment]
> I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.
> 
> Please add a license file - if you don't have one in mind, I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.
> 
> Thanks!

Just seeing this now! Will add a license file today.

Edit: Good to go!
